# Generated by Django 4.2 on 2026-03-09 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('insurance_number', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_notes', models.TextField()),
                ('family_name', models.CharField(max_length=100)),
                ('family_phone', models.CharField(max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
